import './globals.css'
import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'
import Image from 'next/image'

const sourceSans3 = Source_Sans_3({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fortnite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sourceSans3.className}>
          <header className="absolute top-0 left-0 right-0 h-[95px] z-[1000] grid grid-cols-[1fr_70%_1fr] items-center text-center justify-center py-5 border-b-2 border-[#FFFFFF10]">
          <span>
            <Image
              alt="Fortnite"
              src="/logo.svg"
              width={142}
              height={39}
              className="m-auto"
            />
          </span>
          <nav className="grid grid-flow-col justify-center gap-7 text-lg">
            <a>Torneios</a>
            <a>Passe de batalha</a>
            <a>V-bucks</a>
            <a>Itens</a>
          </nav>
          <span>
            <button className="font-logo text-4xl px-10 py-1 bg-button-hover-bg bg-no-repeat bg-center bg-95% bg-yellow-200 hover:bg-yellow-400 transition-all">
              <span className="text-gradient bg-gradient-to-b from-[#21294C] to-[#36426C]">Conheça</span>
            </button>
          </span>
        </header>
        {children}
      </body>
    </html>
  )
}
